databaseChangeLog:
  - changeSet:
      id: 1
      author: imosia
      changes:
        - createTable:
            tableName: allowed_users
            columns:
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    primaryKey: true
                    nullable: false
  - changeSet:
      id: 2
      author: imosia
      changes:
        - createTable:
            tableName: user_balances
            columns:
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    primaryKey: true
              - column:
                  name: balance
                  type: NUMERIC(10,2)
                  constraints:
                    nullable: false
              - column:
                  name: images_generated
                  type: INT
                  constraints:
                    nullable: false
                    defaultValueNumeric: 0
        - addForeignKeyConstraint:
            baseTableName: user_balances
            baseColumnNames: user_id
            constraintName: fk_user_balances_user_id
            referencedTableName: allowed_users
            referencedColumnNames: user_id
            onDelete: CASCADE
  - changeSet:
      id: 3
      author: imosia
      changes:
        - createTable:
            tableName: user_requests
            columns:
              - column:
                  name: timestamp
                  type: TIMESTAMP
              - column:
                  name: user_id
                  type: BIGINT
              - column:
                  name: generation_id
                  type: varchar(255)
                  constraints:
                    primaryKey: true
              - column:
                  name: user_inquery
                  type: TEXT
              - column:
                  name: inquery_type
                  type: varchar(255)
  - changeSet:
      id: 4
      author: imosia
      changes:
        - createTable:
            tableName: machine_responses
            columns:
              - column:
                  name: generation_id
                  type: varchar(255)
                  constraints:
                    primaryKey: true
              - column:
                  name: data_type
                  type: varchar(255)
              - column:
                  name: ai_response
                  type: TEXT
             