replicaCount: 1
commitHash: ""

image:
  repository: ghcr.io/imosia/danilevich_gpt_bot_user_manager
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

container:
  port: 5000

service:
  port: 5000

secret:
  name: app-secrets

ingress:
  enabled: true
  host: um_imosia.danilevich-it-school.com